### PR TITLE
Add jsDoc dependency

### PR DESCRIPTION
**Pull request by kamilkoterba**
https://github.com/Wikia/app/pull/9071

@lizlux

### CODE REVIEW

**Comment by lizlux** [comment]
Hm, I'm getting an error when trying to commit a change to the app repo. Steps to reproduce: 
* Check out this branch `JSCS-dependency` in the guidelines repo
* Check out `JSCS-fix-after-update` in the app repo
* Run `npm install` in the app repo
* Make a change to a js file in the app repo
* Try to commit the change

Result: I get an error from JSCS: `Error: Unsupported rules: plugins`. 

@kamilkoterba, is there a step that I'm missing?

**Comment by drets** [comment]
Related PR: https://github.com/Wikia/guidelines/pull/101

**Comment by lizlux** [comment]
After updating my version of JSCS, I tried the same steps as above, and the error I get now is "plugin should be a function"

**Comment by lizlux** [comment]
Added a package.json to manage dependencies and everything works fine now. Would be good to send out an email to engineering letting them know they should pull the guidelines repo and run `npm install` inside the JavaScript directory. 

Thanks @kamilkoterba for keeping up on this!

**Pull request merged**
