### PR TITLE
Suggest using HideComponent as a guideline

### PR DESCRIPTION
**Pull request by jamieshepherd**
## Description
Let's try to enforce using `HideComponent` where possible for conditional rendering of react components. There are some cases where using conditional logic in JSX might make sense - but almost always we can use `HideComponent`, so this guideline is a _SHOULD_.

## By when to collect feedback?
March 6th 2019

## Who Might Be Interested?
@Wikia/cake

### CODE REVIEW

**Comment by jamieshepherd** [comment]
@mklucsarits I think your opinion absolutely matters - we should always be open minded - and I think for guidelines we should probably come to some consensus and agreement rather than a "this vote was higher" for things to go through.

**Comment by mklucsarits** [comment]
@jamieshepherd I don't really mind using `HideComponent` but I think it comes down to personal preference. My preference is always for practicality and simplicity, _unless_ it affects code readability. Then "explicit is better than implicit" overrides that for me. If we're staking this as a code readability issue, and `HideComponent` is easier to parse than `&&` syntax for someone, then I can understand that angle.

**Comment by JoshuaRogan** [comment]
@mklucsarits I second that your opinion 100% matters. It's always good to have opposition questioning things. 

Ultimately, I agree with Jamie because it makes our render function just JSX rather than mixing some arbitrary javascript. It's cleaner and more explicit

**Comment by cschucode** [comment]
At this point, I agree with simplicity and consistency across components. The `HideComponent` does add another nested layer, but in terms of readability and functionality it works. I have already seen several cases where we needed conditional logic for showing/hiding a component and I imagine as our app grows in complexity there will be even more. As we move forward, this seems like a good point to be consistent with our **use** of `HideComponent`.

**Pull request merged**
