### PR TITLE
Java guidelines init

### PR DESCRIPTION
**Pull request by sqreek**
initial informations

### CODE REVIEW

**Comment by drsnyder** [comment]
@jogura @jimmordino @cmiller-wikia any comments about the proposed style guide?

**Comment by ArturKlajnerok** [comment]
Google guidelines are always LGTM :+1:

**Comment by jimmordino** [comment]
:+1:  No issue with deferring to Google style guidelines initially as long as we're open to making exceptions if we agree they make sense for our organization.

**Comment by ludwikkazmierczak** [comment]
Just two things:
1. Can we use tabs instead of spaces for indentation?
2. Can we increase  column limit from 80 to 100? (80 is a default in a formatter file)

Instead of using two different formatters (for InteliJ and Eclipse) w can use the same for both IDEs - to import formatter for Eclipse to intelliJ we can use [Eclipse Code Formatter(http://plugins.jetbrains.com/plugin/6546) plugin

**Comment by pchojnacki** [comment]
I added more text to README because I like typing letters.
As discussed offline, arch-team is OK with this.  And Ludwik is OK with using spaces instead of Tabs :)

**Pull request merged**
