### PR TITLE
Don't use space before parentheses when defining method through short…

### PR DESCRIPTION
**Pull request by bkoval**
…hand

@hakubo @rogatty @vforge @Warkot @bognix @tomasznapieralski

### CODE REVIEW

**Comment by vforge** [comment]
Awesome!

**Comment by rogatty** [comment]
Well, that's what we do for some time now. Makes sense to have it here.
LGTM

**Comment by bognix** [comment]
LGTM!

**Comment by Warkot** [comment]
LGTM :sparkling_heart:

**Pull request merged**
